#  title: "Ahmad Shahzad"
# description: "AI Automation Architect · GPT Agents · CRM Workflows · AWS"
# url: "https://bd047.github.io"

# # ✅ Pin to a Jekyll-3 compatible release
# remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# plugins:
#   - jekyll-remote-theme
#   - jekyll-seo-tag
#   - jekyll-sitemap
#   - jekyll-feed
#   - jekyll-paginate

# markdown: kramdown
# kramdown:
#   input: GFM

title: "Ahmad Shahzad"
description: "AI Automation Architect · GPT Agents · CRM Workflows · AWS"
url: "https://bd047.github.io"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

markdown: kramdown
kramdown:
  input: GFM

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: single
      author_profile: true

